server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/serviceFallBack
        - id: BRAND-SERVICE
          uri: lb://BRAND-SERVICE
          predicates:
            - Path=/brands/**
          filters:
            - name: CircuitBreaker
              args:
                name: BRAND-SERVICE
                fallbackuri: forward:/serviceFallBack
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/serviceFallBack
        - id: PAID-ORDER-SERVICE
          uri: lb://PAID-ORDER-SERVICE
          predicates:
            - Path=/paid-orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: PAID-ORDER-SERVICE
                fallbackuri: forward:/serviceFallBack
  lifecycle:
    timeout-per-shutdown-phase: 20s

management:
  endpoints:
    web:
      exposure:
        include: "*"
